Asset sync and kube dependency update for OpenShift 4.16 GA
openshift/ibm-roks-toolkit pull request #1075
Opened 2024-08-05 18:41 UTC by Evan-Reilly

2024-08-05 18:44 UTC, rtheis commented
/ok-to-test

2024-08-05 18:54 UTC, rtheis requested changes
Please run `make bindata` and fix the PR test failures.

2024-08-05 21:26 UTC, rtheis requested changes
PR tests are failing. It appears that you'll need to change more than just the Go dependencies.

```

Golang errors in file: []:
  > [line 0 : column 0] - # command-line-arguments
pkg/controllers/openshiftcontrollermanager/operator_client.go:39:9: cannot use &cmOperatorClient{…} (value of type *cmOperatorClient) as v1helpers.OperatorClient value in return statement: *cmOperatorClient does not implement v1helpers.OperatorClient (missing method GetOperatorStateWithQuorum)
  > [line 0 : column 0] - # command-line-arguments
pkg/controllers/openshiftapiserver/controller.go:103:9: cannot use &apiServerOperatorClient{…} (value of type *apiServerOperatorClient) as v1helpers.OperatorClient value in return statement: *apiServerOperatorClient does not implement v1helpers.OperatorClient (missing method GetOperatorStateWithQuorum)
Golang errors in file: [/go/src/github.com/openshift/ibm-roks-toolkit/pkg/controllers/openshiftapiserver/controller.go]:
  > [line 103 : column 9] - cannot use &(apiServerOperatorClient literal) (value of type *apiServerOperatorClient) as v1helpers.OperatorClient value in return statement: *apiServerOperatorClient does not implement v1helpers.OperatorClient (missing method GetOperatorStateWithQuorum)
Golang errors in file: [/go/src/github.com/openshift/ibm-roks-toolkit/pkg/controllers/openshiftcontrollermanager/operator_client.go]:
  > [line 39 : column 9] - cannot use &(cmOperatorClient literal) (value of type *cmOperatorClient) as v1helpers.OperatorClient value in return statement: *cmOperatorClient does not implement v1helpers.OperatorClient (missing method GetOperatorStateWithQuorum)
Summary:
  Gosec  : 2.14.0
  Files  : 34
  Lines  : 11693
  Nosec  : 7
  Issues : 0 
```

2024-08-12 20:48 UTC, jonesbr17 requested changes

2024-08-12 20:48 UTC, jonesbr17 commented on go.mod
> +	k8s.io/client-go v1.5.2
We want this to stay in line with the rest of the k8s deps, so it should be at `v0.29.7`

2024-08-13 16:35 UTC, rtheis approved these changes
/lgtm
/approved

@jonesbr17 ptal

2024-08-13 16:35 UTC, rtheis commented
/hold

2024-08-13 16:48 UTC, jonesbr17 approved these changes
/lgtm
/approve

2024-08-13 17:11 UTC, rtheis commented
/remove-hold

2024-08-13 17:12 UTC, rtheis commented
/cherry-pick release-4.16

2024-08-13 17:15 UTC, merged

2024-08-13 17:23 UTC, rtheis commented
/cherry-pick release-4.16

2024-08-13 17:24 UTC, rtheis commented
@Evan-Reilly you need to manually cherry-pick this PR to 4.16.