Add Portieris container resource requests, remove readiness probe
openshift/ibm-roks-toolkit pull request #113
Opened 2020-11-23 18:10 UTC by lucaspalm

2020-11-23 20:05 UTC, rtheis requested changes
Please support customizing resources and probes like is done for KMS.

2020-11-24 17:31 UTC, rtheis requested changes

2020-11-24 17:31 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +          initialDelaySeconds: 120
Please add the probe configuration support as well.

2020-11-25 12:39 UTC, rtheis requested changes

2020-11-25 12:39 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +{{ if .KubeAPIServerSecurity }}
Please leave the security context work to https://github.com/openshift/ibm-roks-toolkit/pull/114.

2020-11-25 18:50 UTC, lucaspalm commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +          - "--kubeconfig=/etc/openshift/kubeconfig/kubeconfig"
Support for this flag is currently under review in https://github.com/IBM/portieris/pull/218

2020-12-01 18:57 UTC, rtheis requested changes

2020-12-01 18:57 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +          - "2>&1"
Do you really need to redirect output to capture it in the container logs?

2020-12-01 18:57 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +          - "-v=4"
This level of verbosity seems a bit too high for the default value.

2020-12-01 18:57 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +            scheme: {{ or $probe.HttpGet.Scheme "HTTP" }}
Shouldn't the default be `HTTPS`?

2020-12-01 22:49 UTC, rtheis requested changes

2020-12-01 22:49 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +{{ end }}
Does this need to be `{{- end }}`?

2020-12-01 22:49 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +          name: kubeconfig
You need to update the volumes to ensure this mount is available when `PortierisEnabled`.  It is only available for `ROKSMetricsImage` at the moment.

2020-12-01 23:22 UTC, lucaspalm commented
@rtheis All your comments/concerns have been addressed so far.

2020-12-02 12:19 UTC, rtheis requested changes

2020-12-02 12:19 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +            path: {{ or $probe.HttpGet.Path "health/liveness" }}
Sorry I missed this on my previous reviews, but the default should be `/health/liveness`.  The leading slash is missing.

2020-12-02 18:00 UTC, rtheis approved these changes
/lgtm

2020-12-02 18:00 UTC, rtheis commented
@csrwng ptal

2020-12-02 18:18 UTC, csrwng commented
I'm seeing:
```
t % ./bin/ibm-roks render                                                                       
panic: template: template:319:7: executing "template" at <.ROKSMetricsImage>: ROKSMetricsImage has arguments but cannot be invoked as function

goroutine 1 [running]:
github.com/openshift/ibm-roks-toolkit/pkg/render.(*renderContext).substituteParams(0xc0010be000, 0x1838e00, 0xc000146900, 0x1b7d39b, 0x2d, 0x45, 0x1bac44f, 0x49, 0x1bafe07)
        /home/cewong/code/ibm-roks-toolkit/pkg/render/rendercontext.go:68 +0x30b
github.com/openshift/ibm-roks-toolkit/pkg/render.(*renderContext).renderManifests(0xc0010be000, 0xc001010001, 0x1838e00)
        /home/cewong/code/ibm-roks-toolkit/pkg/render/rendercontext.go:39 +0x2eb
github.com/openshift/ibm-roks-toolkit/pkg/render.RenderClusterManifests(0xc000146900, 0xc000376640, 0x32, 0xc00011a2a0, 0x2c, 0xc000dc0001, 0xc000dcfd88, 0xc000dcfd88)
        /home/cewong/code/ibm-roks-toolkit/pkg/render/manifests.go:23 +0x139
github.com/openshift/ibm-roks-toolkit/pkg/cmd/render.(*RenderManifestsOptions).Run(0xc00032e400, 0x1b4089c, 0x4)
        /home/cewong/code/ibm-roks-toolkit/pkg/cmd/render/manifests.go:48 +0x14c
github.com/openshift/ibm-roks-toolkit/pkg/cmd/render.NewRenderManifestsCommand.func1(0xc000e88840, 0x29f7010, 0x0, 0x0)
        /home/cewong/code/ibm-roks-toolkit/pkg/cmd/render/manifests.go:26 +0x2e
github.com/spf13/cobra.(*Command).execute(0xc000e88840, 0x29f7010, 0x0, 0x0, 0xc000e88840, 0x29f7010)
        /home/cewong/code/ibm-roks-toolkit/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e88580, 0xc000dcff70, 0x1, 0x1)
        /home/cewong/code/ibm-roks-toolkit/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/cewong/code/ibm-roks-toolkit/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /home/cewong/code/ibm-roks-toolkit/cmd/ibm-roks/main.go:12 +0xb3
```
which I don't get running render with the master branch
I suspect it's being caused by:
https://github.com/openshift/ibm-roks-toolkit/pull/113/files#diff-8b7c5159d658cb2b12ea1b22b94ce9efc30358c9d47a47c6fde717ac9c3a7ca1R319

2020-12-02 18:42 UTC, lucaspalm commented
The "or" operator must not be acceptable there?  Whats the proper way to do that?

2020-12-02 19:45 UTC, csrwng commented
@lucaspalm I think the right syntax is `if or .ROKSMetricsImage .PortierisEnabled` (since `or` is considered a function with 2 params)

2020-12-02 20:32 UTC, lucaspalm commented
@csrwng Yep that's what I changed it too.  See if that works now...

2020-12-02 20:48 UTC, csrwng commented
/lgtm
/approve

2020-12-02 20:53 UTC, csrwng commented
@lucaspalm if you think it's ready, remove the wip tag

2020-12-02 20:54 UTC, lucaspalm commented
@csrwng Let me finish up some testing with it first before I am happy removing the tag.

2020-12-04 19:39 UTC, rtheis approved these changes
/lgtm

2020-12-04 20:22 UTC, lucaspalm commented
@rtheis FYI the latest push was to add back in the logging flags.  Without them, there are basically no helpful logs...

@csrwng My testing looks good.  This is ready when you and are.

2020-12-04 21:36 UTC, rtheis approved these changes
/lgtm

2020-12-04 22:44 UTC, lucaspalm commented
I guess im not sure why the tests are now failing...
```
error: some steps failed:
  * could not run steps: step src failed: the build src failed after 14s with reason FetchImageContentFailed: Failed to extract image content. 
```
Compared to the previous passing build, all I did was rebase and add a couple starting command args.

Locally, `make verify` looks good.

2020-12-04 23:11 UTC, csrwng commented
/retest

2020-12-05 12:59 UTC, csrwng commented
/lgtm

2020-12-05 13:02 UTC, merged

2020-12-07 14:17 UTC, csrwng commented
/cherry-pick release-4.6

2020-12-07 15:24 UTC, csrwng commented
/cherry-pick release-4.6