Add securityContext to Bootstrapper, cluster-policy-controller and oauth-server
openshift/ibm-roks-toolkit pull request #120
Opened 2020-12-08 21:31 UTC by Joseph-Goergen

2020-12-08 21:47 UTC, rtheis requested changes

2020-12-08 21:47 UTC, rtheis commented on assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
> +{{- if .BootstrapperSecurityContext }}
There is an init container that need a security context in this deployment.

2020-12-08 21:47 UTC, rtheis commented on assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
> +{{- if .BootstrapperSecurityContext }}
I would prefer `ManifestBootstrapper` instead of `Bootstrapper` prefix.

2020-12-08 23:48 UTC, csrwng commented
@Joseph-Goergen should the 2nd init container in the manifest bootstrapper pod also have a securityContext ?

2020-12-09 17:00 UTC, rtheis requested changes

2020-12-09 17:00 UTC, rtheis commented on pkg/api/types.go
> +	ClusterConfigOperator                     *SecurityContext       `json:"clusterConfigOperator"`
Please use `ClusterConfigOperatorSecurityContext`

2020-12-09 17:29 UTC, rtheis requested changes

2020-12-09 17:29 UTC, rtheis commented on assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
> +{{- if .ClusterConfigOperator }}
This needs to be `ClusterConfigOperatorSecurityContext`.

2020-12-09 17:29 UTC, rtheis commented on assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
> +{{- $securityContext := .ClusterConfigOperator }}
This needs to be `ClusterConfigOperatorSecurityContext`.

2020-12-09 19:31 UTC, rtheis approved these changes
/lgtm

2020-12-09 19:31 UTC, rtheis commented
@csrwng ptal

2020-12-10 01:41 UTC, csrwng commented
/lgtm
/approve

2020-12-10 01:44 UTC, merged

2020-12-10 02:16 UTC, rtheis commented
@Joseph-Goergen Can you please cherry-pick to 4.4, 4.5 and 4.6?  Thanks.

2020-12-10 14:23 UTC, Joseph-Goergen commented
/cherry-pick release-4.6

2020-12-10 14:24 UTC, Joseph-Goergen commented
/cherry-pick release-4.5

2020-12-10 14:24 UTC, Joseph-Goergen commented
/cherry-pick release-4.4