Changed runAsNonRoot to runAsUser for roks metrics
openshift/ibm-roks-toolkit pull request #134
Opened 2021-01-07 22:52 UTC by Joseph-Goergen

Kept failing with
```
          "waiting": {
            "message": "container has runAsNonRoot and image will run as root",
            "reason": "CreateContainerConfigError"
          }
```
Seems to be running fine when `runAsUser: 1000` is set

2021-01-08 10:44 UTC, rtheis requested changes

2021-01-08 10:44 UTC, rtheis commented on assets/roks-metrics/roks-metrics-deployment.yaml
> +          runAsUser: {{ $securityContext.RunAsUser }}
Per our discussion, this should continue to use `runAsNonRoot` since we don't know the UID.

2021-01-08 10:44 UTC, rtheis commented on assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
> +          runAsUser: {{ $securityContext.RunAsUser }}
Per our discussion, this should continue to use `runAsNonRoot` since we don't know the UID.

2021-01-08 15:08 UTC, csrwng commented
/retest

2021-01-08 17:35 UTC, rtheis requested changes

2021-01-08 17:35 UTC, rtheis commented on pkg/assets/bindata.go
> +          runAsUser: {{ $securityContext.RunAsNonRoot }}
This should be `runAsNonRoot`.

2021-01-08 17:35 UTC, rtheis commented on pkg/assets/bindata.go
> +          runAsUser: {{ $securityContext.RunAsNonRoot }}
This should be `runAsNonRoot`.

2021-01-08 17:35 UTC, rtheis commented on assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
> +          runAsUser: {{ $securityContext.RunAsNonRoot }}
This should be `runAsNonRoot`.

2021-01-08 17:35 UTC, rtheis commented on assets/roks-metrics/roks-metrics-deployment.yaml
> +          runAsUser: {{ $securityContext.RunAsNonRoot }}
This should be `runAsNonRoot`.

2021-01-08 17:58 UTC, rtheis requested changes

2021-01-08 17:58 UTC, rtheis commented on assets/roks-metrics/roks-metrics-deployment.yaml
> +{{- if .ROKSMetricsSecurityContextMaster }}
This needs to be the worker context.

2021-01-08 17:58 UTC, rtheis commented on assets/roks-metrics/roks-metrics-deployment.yaml
> +{{- $securityContext := .ROKSMetricsSecurityContextMaster }}
This needs to be the worker context.

2021-01-08 18:44 UTC, rtheis approved these changes
/lgtm

2021-01-08 18:44 UTC, rtheis commented
/assign @csrwng

2021-01-11 14:24 UTC, csrwng commented
/lgtm
/approve

2021-01-11 14:25 UTC, Joseph-Goergen commented
/cherry-pick release-4.6

2021-01-11 14:25 UTC, Joseph-Goergen commented
/cherry-pick release-4.5

2021-01-11 14:25 UTC, jonesbr17 approved these changes

2021-01-11 14:49 UTC, merged