Add Host_IP to kube-apiserver deployment to fix apirequestcount errors in ROKS 4.8
openshift/ibm-roks-toolkit pull request #429
Opened 2022-03-07 20:06 UTC by SmithaSubbarao

Related to this issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2902

**DNM until test results have been shared below**

2022-03-07 20:09 UTC, SmithaSubbarao commented
I will need to verify the location of the ```HOST_IP``` based on the tests in stage for ROKS 4.8 -> currently locked out to due authentication errors.

2022-03-07 20:14 UTC, SmithaSubbarao commented
Updating bindata.go

2022-03-08 13:22 UTC, rtheis commented
/ok-to-test

2022-03-08 13:23 UTC, rtheis requested changes

2022-03-08 13:23 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> +        - name: HOST_IP
This was added to the wrong container.  This is the KMS container not the Kubernetes API server container.

2022-03-09 14:03 UTC, rtheis approved these changes
/lgtm
/approved

2022-03-09 20:34 UTC, SmithaSubbarao commented
Fixing the go module errors in the local branch:

Running into errors in the ```build:  bindata control-plane-operator roks-metrics``` step in the latest ```make build``` run:

```
➜  ibm-roks-toolkit git:(add-hostip-to-kubeapiserver) ✗ make build       git:(add-hostip-to-kubeapiserver|✚1 
hack/update-generated-bindata.sh
go build -mod=vendor -o ./bin/control-plane-operator ./cmd/control-plane-operator/main.go
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
make: *** [control-plane-operator] Error 2
```

2022-03-09 21:22 UTC, SmithaSubbarao commented
Updated go version to 1.17 ( since 1.16 is outdated) and fixed the errors.

2022-03-15 11:16 UTC, rtheis commented
@SmithaSubbarao have you been able to complete your testing of this change?

2022-03-15 17:43 UTC, SmithaSubbarao commented
Created a new [release](https://github.com/SmithaSubbarao/ibm-roks-toolkit/releases/tag/v3.0-add-host-ip-kube-apiserver) with the latest ibm roks toolkit build (using the vagrant verify method) and published a new custom test BOM: https://alchemy-containers-jenkins.swg-devops.com/job/Containers-Runtime/job/armada-test-bom-publish/8746/

2022-03-15 22:33 UTC, SmithaSubbarao commented
The latest test BOM finally passed! https://alchemy-containers-jenkins.swg-devops.com/job/Containers-Runtime/job/armada-test-bom-publish/8755/

2022-03-17 19:58 UTC, rtheis commented on .secrets.baseline
> +        "line_number": 3128,
I recommend removing this from the PR so we can cherry-pick this fix.  Then you can fix the secrets baseline in a separate PR.

2022-03-17 21:55 UTC, SmithaSubbarao commented
The latest test BOM finally passed after many kube-addons failures, but the ROKS 4.10 cluster failed to deploy for the same reasons as the previous deploy failures -> the roks toolkit binary is not found in the path ```/armada-openshift-master/lib/roks4/bin/ibm-roks```:

```
2022-03-17 21:35:41,211 p=27 u=nonroot n=ansible | TASK [check for binary first] **************************************************
2022-03-17 21:35:41,212 p=27 u=nonroot n=ansible | Thursday 17 March 2022  21:35:41 +0000 (0:00:00.038)       0:00:04.247 ******** 
2022-03-17 21:35:41,235 p=100 u=nonroot n=ansible | <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: nonroot
2022-03-17 21:35:41,235 p=100 u=nonroot n=ansible | <127.0.0.1> EXEC /bin/sh -c 'echo ~nonroot && sleep 0'
2022-03-17 21:35:41,273 p=100 u=nonroot n=ansible | <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/nonroot/.ansible/tmp `"&& mkdir "` echo /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888 `" && echo ansible-tmp-1647552941.2717745-100-61658967531888="` echo /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888 `" ) && sleep 0'
2022-03-17 21:35:41,544 p=100 u=nonroot n=ansible | Using module file /opt/app-root/lib64/python3.9/site-packages/ansible/modules/stat.py
2022-03-17 21:35:41,546 p=100 u=nonroot n=ansible | <127.0.0.1> PUT /home/nonroot/.ansible/tmp/ansible-local-27x43vk49p/tmpicov5mfi TO /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888/AnsiballZ_stat.py
2022-03-17 21:35:41,547 p=100 u=nonroot n=ansible | <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888/ /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888/AnsiballZ_stat.py && sleep 0'
2022-03-17 21:35:41,632 p=100 u=nonroot n=ansible | <127.0.0.1> EXEC /bin/sh -c '/opt/app-root/bin/python3 /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888/AnsiballZ_stat.py && sleep 0'
2022-03-17 21:35:41,879 p=100 u=nonroot n=ansible | <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/nonroot/.ansible/tmp/ansible-tmp-1647552941.2717745-100-61658967531888/ > /dev/null 2>&1 && sleep 0'
2022-03-17 21:35:41,934 p=27 u=nonroot n=ansible | ok: [localhost] => changed=false 
  invocation:
    module_args:
      checksum_algorithm: sha1
      follow: false
      get_attributes: true
      get_checksum: true
      get_md5: false
      get_mime: true
      path: /armada-openshift-master/lib/roks4/bin/ibm-roks
  stat:
    exists: false
2022-03-17 21:35:41,954 p=27 u=nonroot n=ansible | TASK [Make sure required variables are defined and valid] **********************
2022-03-17 21:35:41,995 p=27 u=nonroot n=ansible | TASK [Make sure roks 4 binary exists when k8s state == present] ****************
2022-03-17 21:35:41,996 p=27 u=nonroot n=ansible | Thursday 17 March 2022  21:35:41 +0000 (0:00:00.040)       0:00:05.031 ******** 
2022-03-17 21:35:42,024 p=27 u=nonroot n=ansible | fatal: [localhost]: FAILED! => changed=false 
  assertion: _roks4_binary.stat.exists
  evaluated_to: false
  msg: Assertion failed
```

Link to deploy failure: https://ibm-argonauts.slack.com/archives/CA9U7HMED/p1647552942898989
Test BOM: https://alchemy-containers-jenkins.swg-devops.com/job/Containers-Runtime/job/armada-test-bom-publish/8787

We confirmed that the armada-kubx-deployer commit is correct and pointed to the right release; 
armada-kubx-deployer commit: https://github.ibm.com/alchemy-containers/armada-kubx-deployer/commit/c7753f280fcc84c56531bfa514de881cf662cead
Toolkit release: https://github.com/SmithaSubbarao/ibm-roks-toolkit/releases/tag/v5.0-add-host-ip-kube-apiserver

2022-03-18 11:14 UTC, rtheis commented
@SmithaSubbarao I found the problem and DM'd you the details.

2022-03-19 15:59 UTC, SmithaSubbarao commented
> @SmithaSubbarao I found the problem and DM'd you the details.

Thank you Richard, I removed the oc_check for 4.10 in the armada-kubx-deployer commit and it worked:

Test BOM: https://alchemy-containers-jenkins.swg-devops.com/job/Containers-Runtime/job/armada-test-bom-publish/8819/
```
Carrier                  BOM                    BOM     Armada Ansible     Armada Openshift Master  Kubx Deployer
                         Version                Type    Branch (SHA)       Branch (SHA)             Branch (SHA)
------                   ------                 ------  ------             ------                   ------
prestage-mon01-carrier1  4.8.33_1119_openshift  next    master (02236a8a)  master (224b1afa)        smitha-toolkit-test (3f8bb096)
prestage-mon01-carrier1  4.9.23_1119_openshift  next    master (02236a8a)  master (224b1afa)        smitha-toolkit-test (3f8bb096)
prestage-mon01-carrier1  4.10.5_1119_openshift  next    master (02236a8a)  master (224b1afa)        smitha-toolkit-test (3f8bb096)
```

Test clusters - deployed and normal:
```
➜  Desktop ibmcloud ks cluster ls
OK
Name             ID                     State     Created      Workers   Location   Version                 Resource Group Name   Provider   
roks-4.10-test   c8qulvr10s95pc5otah0   warning   1 hour ago   3         Dallas     4.10.5_1119_openshift   Default               classic   
roks-4.9-test    c8qum9m10m4iq8o2fd20   warning   1 hour ago   3         Dallas     4.9.23_1119_openshift   Default               classic   
```

2022-03-19 16:05 UTC, SmithaSubbarao commented
The apirequestcount commands work correctly for the 4.10 and 4.9 clusters:

```
➜  Desktop oc get apirequestcounts
NAME                                                                       REMOVEDINRELEASE   REQUESTSINCURRENTHOUR   REQUESTSINLAST24H
alertmanagerconfigs.v1alpha1.monitoring.coreos.com                                            22                      27
alertmanagers.v1.monitoring.coreos.com                                                        122                     128
apirequestcounts.v1.apiserver.openshift.io                                                    12396                   13704
apiservers.v1.config.openshift.io                                                             99                      110
apiservers.v1.operator.tigera.io                                                              20                      25
apiservices.v1.apiregistration.k8s.io                                                         571                     1101
authentications.v1.config.openshift.io                                                        27                      35
bgpconfigurations.v1.crd.projectcalico.org                                                    33                      36
bgppeers.v1.crd.projectcalico.org                                                             20                      25
blockaffinities.v1.crd.projectcalico.org                                                      216                     221
brokertemplateinstances.v1.template.openshift.io                                              12                      17
buildconfigs.v1.build.openshift.io                                                            43                      79
builds.v1.build.openshift.io                                                                  57                      113
builds.v1.config.openshift.io                                                                 45                      62
caliconodestatuses.v1.crd.projectcalico.org                                                   2262                    2262
catalogsources.v1alpha1.operators.coreos.com                                                  185                     190
certificatesigningrequests.v1.certificates.k8s.io                                             113                     128
clustercsidrivers.v1.operator.openshift.io                                                    24                      29
clusterinformations.v1.crd.projectcalico.org                                                  437                     442
clusteroperators.v1.config.openshift.io                                                       1566                    1640
clusterresourcequotas.v1.quota.openshift.io                                                   84                      185
clusterrolebindings.v1.rbac.authorization.k8s.io                                              2548                    3264
clusterroles.v1.rbac.authorization.k8s.io                                                     2663                    3818
clusterserviceversions.v1alpha1.operators.coreos.com                                          69                      74
clusterversions.v1.config.openshift.io                                                        432                     461
configmaps.v1                                                                                 19848                   21041
configs.v1.imageregistry.operator.openshift.io                                                39                      44
configs.v1.operator.openshift.io                                                              24                      32
configs.v1.samples.operator.openshift.io                                                      24                      29
consoleclidownloads.v1.console.openshift.io                                                   219                     233
consoleexternalloglinks.v1.console.openshift.io                                               12                      17
consolelinks.v1.console.openshift.io                                                          58                      88
consolenotifications.v1.console.openshift.io                                                  10                      15
consoleplugins.v1alpha1.console.openshift.io                                                  22                      27
consolequickstarts.v1.console.openshift.io                                                    167                     172
consoles.v1.config.openshift.io                                                               153                     160
consoles.v1.operator.openshift.io                                                             1242                    1251
consoleyamlsamples.v1.console.openshift.io                                                    11                      16
containerruntimeconfigs.v1.machineconfiguration.openshift.io                                  11                      16
controllerrevisions.v1.apps                                                                   38                      55
credentialsrequests.v1.cloudcredential.openshift.io                                           246                     305
cronjobs.v1.batch                                                                             278                     304
cronjobs.v1beta1.batch                                                     1.25               11                      11
csidrivers.v1.storage.k8s.io                                                                  81                      101
csinodes.v1.storage.k8s.io                                                                    51                      69
csisnapshotcontrollers.v1.operator.openshift.io                                               88                      96
csistoragecapacities.v1beta1.storage.k8s.io                                                   48                      78
customresourcedefinitions.v1.apiextensions.k8s.io                                             1733                    2284
daemonsets.v1.apps                                                                            1180                    1227
deploymentconfigs.v1.apps.openshift.io                                                        40                      72
deployments.v1.apps                                                                           4154                    4390
dnses.v1.config.openshift.io                                                                  80                      95
dnses.v1.operator.openshift.io                                                                84                      90
dnsrecords.v1.ingress.operator.openshift.io                                                   121                     126
egressrouters.v1.network.operator.openshift.io                                                20                      25
endpoints.v1                                                                                  2409                    2636
endpointslices.v1.discovery.k8s.io                                                            1367                    1612
endpointslices.v1beta1.discovery.k8s.io                                    1.25               10                      10
etcds.v1.operator.openshift.io                                                                22                      31
events.v1                                                                                     2188                    2504
events.v1.events.k8s.io                                                                       31                      42
featuregates.v1.config.openshift.io                                                           177                     190
felixconfigurations.v1.crd.projectcalico.org                                                  39                      44
flowschemas.v1beta1.flowcontrol.apiserver.k8s.io                                [...]

2022-03-21 11:16 UTC, rtheis approved these changes
/remove-hold

2022-03-21 11:17 UTC, rtheis approved these changes
/lgtm
/approved

2022-03-21 11:22 UTC, merged

2022-03-21 11:23 UTC, rtheis commented
/cherry-pick release-4.10

2022-03-21 11:23 UTC, rtheis commented
/cherry-pick release-4.9

2022-03-21 11:23 UTC, rtheis commented
/cherry-pick release-4.8