Add openshift.io/cluster-monitoring label to ns
openshift/ibm-roks-toolkit pull request #615
Opened 2022-08-11 03:28 UTC by jmcmeek

When user workload monitoring is enabled, we get alerts related to
ServiceMonitors using bearer tokens. Adding the
openshift.io/cluster-monitoring="true" label is the standard way to fix
this - most openshift-* namespaces have this label.

2022-08-11 11:24 UTC, rtheis requested changes
You will need to run `make bindata` to regenerate bindata.go

2022-08-11 15:34 UTC, jmcmeek commented
@rtheis  Finally found my directions for generating bindata - which didn't work any more.  bindata is no included and PR checks are happier.

2022-08-11 17:40 UTC, csrwng commented
@jmcmeek I don't think this is the best way to fix UWM. Even though UWM will stop reporting errors, the regular platform monitoring stack will now think it needs to scrape service monitors in these namespaces. 
A better approach would be to exclude them from uwm monitoring:
https://docs.openshift.com/container-platform/4.11/monitoring/enabling-monitoring-for-user-defined-projects.html#excluding-a-user-defined-project-from-monitoring_enabling-monitoring-for-user-defined-projects
with `'openshift.io/user-monitoring=false'`

2022-08-11 18:22 UTC, rtheis reviewed
Why don't we disable monitoring for most if not all of these namespaces?

2022-08-11 21:40 UTC, csrwng commented
That makes sense to me.

2022-08-12 14:14 UTC, jmcmeek commented
It looks like that works.  I'll get to that later.  Just ran out of time for now.

2022-08-18 17:52 UTC, rtheis requested changes
Can you please explain why some of these namespaces set `openshift.io/user-monitoring`, others set `openshift.io/cluster-monitoring` and other have neither?  It may be nice to include a comment for future reference.

2022-08-19 02:43 UTC, jmcmeek commented
To the extent the namespaces are related to core components, OCP would normally label them `openshift.io/cluster-monitoring="true"`, as are the other namespaces in this manifest.  Personally, I think `openshift.io/user-monitoring="false"`  is intended for namespaces that are properly part of user workload monitoring but the administrator does not want them to be monitored.

The alert itself:
`level=warn ts=2022-07-25T05:52:33.981419693Z caller=operator.go:1832 component=prometheusoperator msg="skipping servicemonitor" error="it accesses file system via bearer token file which Prometheus specification prohibits" servicemonitor=openshift-apiserver/openshift-apiserver namespace=openshift-user-workload-monitoring prometheus=user-workload`

appears for a few reasons:
1) The ServiceMonitors specify `bearerTokenFile`, which is considered a potential security risk (someone who can create a ServiceMonitor can specify any path within the prometheus file system, and prometheus could send the contents of that file as the bearer token).  `bearerTokenSecret` is better (but painful), or TLS authentication - again avoiding the use of a file.
2) Lacking any labels, these namespaces are fair game for user workload monitoring.
3) The alert flags such servicemonitors as broken and the owner of the servicemonitor is supposed to fix it.

If I can find it again... which I haven't...

The openshift-monitoring prometheus instance uses `ArbitraryFSAccessThroughSMsConfig.Deny: false` and the user workload instance uses `ArbitraryFSAccessThroughSMsConfig.Deny: true`.  There is work (maybe in progress, some release) for the cluster monitoring side to be converted to use TLS authentication (using the ServiceMonitor "xxxSecret" fields (not "xxxFile"), at which point I assume the openshift-monitoring prometheus instance will also use `ArbitraryFSAccessThroughSMsConfig.Deny: "true"`.

Which makes the problems, in no particular order:
- The 3 namespaces in this PR shouldn't have ServiceMonitors in ROKS - there is nothing to monitor
- Given they do have ServiceMonitors, and are not user workloads, these namespaces are not labeled properly for inclusion in cluster monitoring (OCP does label them).
- Any ServiceMonitor included in cluster monitoring should eventually be using TLS authentication with the ServiceMonitor configured to use secrets.

Short term we should label these.  Longer term these ServiceMonitors (and any others we install) need to be addressed.

2022-08-19 16:02 UTC, rtheis approved these changes
/lgtm
/approved

I still don't understand but trust you.

2022-08-19 16:26 UTC, merged

2022-08-19 16:31 UTC, rtheis commented
/cherry-pick release-4.11

2022-08-19 16:32 UTC, rtheis commented
/cherry-pick release-4.10