[DNM] featuregate information now required
openshift/ibm-roks-toolkit pull request #775
Opened 2023-07-24 19:53 UTC by jeffnowicki

During ROKS 4.14 bringup, it was was discovered that `featuregate` information is now required.

```
$ kubectl logs -n master-cin9ks420488vf8s9beg kube-apiserver-54757949cd-jz4gd -c config-bootstrap
 
F0712 17:27:36.225575       8 render.go:53] problem with featuregate manifests: cannot return FeatureGate without rendered manifests
cp: cannot stat '/tmp/output/manifests/*': No such file or directory
```

2023-07-24 21:45 UTC, rtheis requested changes

2023-07-24 21:45 UTC, rtheis commented on assets/kube-apiserver/featuregate.yaml
> +{% if k8s_feature_gates is defined %}
Please use the toolkit version of `k8s_feature_gates` ROKS data which is `DefaultFeatureGates` and `ExtraFeatureGates`.

2023-07-24 21:45 UTC, rtheis commented on assets/kube-apiserver/kube-apiserver-deployment.yaml
> ++         /usr/bin/cluster-config-operator render --config-output-file config --asset-input-dir /tmp/input --asset-output-dir /tmp/output --rendered-manifest-files /tmp/input/cluster-featuregate.yaml
We should only need one render.  I'm not sure if `cp /features/cluster-featuregate.yaml /tmp/input` is sufficient to satisfy the current render or if we indeed need `--rendered-manifest-files /tmp/input/cluster-featuregate.yaml`.

2023-07-26 20:12 UTC, jeffnowicki commented
@rtheis I statically set the enabled/disabled featuregates in `featuregate.yaml`. At the moment, I don't have a go text/template based solution to process the `ExtraFeatureGates` info that our ansible produces.

This is a 'tactical' step so we can get a functional pipeline up (with initial worker bom when available later this week). Once I've come up with a solution, I'll put up a PR and we can publish a new toolkit release.

2023-07-28 10:44 UTC, rtheis approved these changes
/lgtm
/approved

2023-07-28 10:49 UTC, merged

2023-07-28 10:53 UTC, rtheis commented
/cherry-pick release-4.14