Asset sync 4.15
openshift/ibm-roks-toolkit pull request #924
Opened 2024-01-10 16:40 UTC by jonesbr17

Sync assets with upstream

2024-01-10 21:53 UTC, rtheis requested changes
Please ensure all new links are valid.  Given parts have moved, we at least need to change the links but may also have functional changes to include.

2024-01-10 21:53 UTC, rtheis commented on assets/cluster-bootstrap/cluster-network-01-crd.yaml
> +# Source: https://github.com/openshift/cluster-network-operator/blob/release-4.15/manifests/0000_70_cluster-network-operator_01_crd.yaml
This link is not valid.

2024-01-10 21:53 UTC, rtheis commented on assets/cluster-bootstrap/deployer-clusterrole.yaml
> +# Source: https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/release-4.15/bindata/v3.11.0/openshift-controller-manager/deployer-clusterrole.yaml
This link is not valid either.

2024-01-11 14:53 UTC, jonesbr17 commented
Fixed the invalid links

2024-01-11 18:27 UTC, rtheis approved these changes
/lgtm
/approved

2024-01-11 18:29 UTC, rtheis commented
/cherry-pick release-4.15

2024-01-11 18:32 UTC, merged